name: Build and test Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi
        if: matrix.os == 'ubuntu-latest'

      - name: Go test
        run: make

      #- name: Build
      #  run: make build OS=${{ matrix.OS }} ARCH=${{ matrix.ARCH }} ARM=${{ matrix.ARM }}
